kind: Secret
apiVersion: v1
metadata:
  name: counter-database
  labels:
    app: counter-database
    app.kubernetes.io/part-of: aufgabe-lb-v1
data:
  database-name: cHdk #pwd
  database-user: cHdk #pwd
  database-password: cHdk #pwd
type: Opaque