apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: counter-frontend
  labels:
    app: counter-frontend
    app.kubernetes.io/part-of: aufgabe-lb-v1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: counter-frontend
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
