kind: Deployment
apiVersion: apps/v1
metadata:
  name: postgresadmin
  labels:
    app: postgresadmin
    app.kubernetes.io/part-of: aufgabe-lb-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresadmin
  template:
    metadata:
      labels:
        app: postgresadmin
        deployment: postgresadmin
    spec:
      containers:
        - name: postgresadmin
          image: ghcr.io/modul-i-ch-109/pgadmin4:latest
          imagePullPolicy: Always
          restartPolicy: Always
          ports:
            - containerPort: 5050
              protocol: TCP
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: counter-database
                  key: database-name
            - name: PGADMIN_DEFAULT_EMAIL
              value: test@test.com
            - name: PGADMIN_DEFAULT_PASSWORD
              value: test
