kind: Service
apiVersion: v1
metadata:
  name: postgresadmin
  labels:
    app: postgresadmin
    app.kubernetes.io/part-of: aufgabe-lb-v1
spec:
  ports:
    - name: 5050-tcp
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: postgresadmin